### ISSUE TITLE
Register package on bower

### ISSUE THREAD

**Issue by marcusbuffett** [oakmac/chessboardjs#101]
It would be nice if I could install this using bower like the rest of my frontend dependencies.

**Comment by oakmac** [comment]
I don't know much about Bower, but I'm not opposed to adding this to the project if it's not too intrusive.

FYI - whenever you add chessboard.js to your website, it puts itself on `window.ChessBoard`

**Comment by oakmac** [comment]
chessboardjs is on [npm](https://www.npmjs.com/package/@chrisoakman/chessboardjs) now
