### ISSUE TITLE
chessboarjs doesn't go well with ionic

### ISSUE THREAD

**Issue by rohandalvi** [oakmac/chessboardjs#104]
I tried to use chessboard js with ionic you can checkout the code in my github repository here https://github.com/rohandalvi/ionicChess/blob/master/www/js/controllers.js .

Here I am using the Integration of chessboardjs with chessjs as provided on the website link to only allow legal moves, here:

http://chessboardjs.com/examples#5000

As you can see from the screenshot below, whenever I try to drag a piece on the board, the piece just disappears until it has been dropped. I am not sure of what the issue is . Here is the screenshot.

<img width="1440" alt="screen shot 2015-08-13 at 10 54 00 pm" src="https://cloud.githubusercontent.com/assets/1272182/9266393/89cb862e-420e-11e5-8362-a1e17458541a.png">

**Comment by rohandalvi** [comment]
As seen in the screenshot, I am trying to play d4 and took the screenshot while I was dragging the piece to the square, the pawn just disappears until I leave the drag. Please let me know if the issue is still not clear. Thanks !

**Comment by fhinson** [comment]
Hi Rohan,

Try adding this to your css.

    .piece-417db {
      z-index: 4000!important;
    }

**Comment by rohandalvi** [comment]
Thanks, that worked!
