### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by ngdaddikar** [oakmac/chessboardjs#106]
This project has a lot of promise. But I see no update for the last two years; it's still v0.3. Is the author thinking of maintaining it or enhancing it?

I'd like to use this in a mobile app. But I don't want to get stuck with an abandoned project.

Thanks.

**Comment by oakmac** [comment]
I'm still around :)

Project doesn't have a lot of activity because it is mostly stable. I plan
to release a v1 when I have some time (See Issue #96).

**Comment by ngdaddikar** [comment]
That’s great to know.

Also, does it work inside native mobile app? I am planning to use Cordova to build it for Android and iOS.

I think it will be a great idea if you can offer one chess engine integration e.g. p4wn. It is relatively well documented.

Do you offer consulting? I am looking for an app developer who will help me build this app with ionic framework.

Thanks.

**Comment by oakmac** [comment]
The board should work on mobile devices. If it does not please open an issue.

I have some examples of integration with the [chess.js](https://github.com/jhlywa/chess.js) library [here](http://chessboardjs.com/examples#5002) and [here](http://chessboardjs.com/examples#5003).

I am not available to consult right now; thank you though :)
