### ISSUE TITLE
How can I display a board inside a popup?

### ISSUE THREAD

**Issue by greenleafone7** [oakmac/chessboardjs#112]
I am trying to create a small n-queen solver and I want to add an interactive board each time a player clicks on the secondary action of a list item. 

The thing is that I am not sure how to initiate the board when it is inside the template code.

Please refer to this [plunk](http://plnkr.co/edit/3jZjV3WPdS7SbPhnQLSN?p=preview) for a better understanding.

**Comment by oakmac** [comment]
It seems this isn't really a question about chessboard.js so much as it is a question about angular / your specific setup. You might have better luck posting this on [StackOverflow](http://www.stackoverflow.com).
