### ISSUE TITLE
Pieces and board themes

### ISSUE THREAD

**Issue by jbkunst** [oakmac/chessboardjs#113]
Hi @oakmac,

Thanks for chessboardjs! I hope you soon retake this awesome project again!

I want to share with you a set of pieces/board themes:

![theme_summary](https://cloud.githubusercontent.com/assets/56481/11429265/42feca06-9454-11e5-9047-5db3d955ddd3.png)

To work there's a little change to make (I made) in chessboardjs: add a function to color the board via javascript and not use the css, and add a boardTheme cfg parameter (a list of two hexadecimal colors). I would like to read your thoughts about this or maybe you have other implementation to get color themes via cfg option.

preview: https://rawgit.com/jbkunst/chessboardjs-themes/master/index.html
repo: https://github.com/jbkunst/chessboardjs-themes

**Comment by oakmac** [comment]
What wonderful work! I will look at including these changes to chessboard.js.

I'm not sure I like the 2-element vector for colors as opposed to an object with some semantic property names, but that's not a big deal.

Using a data-uri should be much faster than referencing an external image file. It would also incidentally fix [Issue #52](https://github.com/oakmac/chessboardjs/issues/52), which is one of the longest-standing issues for this project.

Thank you for this contribution :)

**Comment by jbkunst** [comment]
Nice news! I hope see v1.0.0 soon :D. If I can help you, let me know.
