### ISSUE TITLE
Question - Possible to change number of columns / rows

### ISSUE THREAD

**Issue by jdell64** [oakmac/chessboardjs#114]
Hey, I realize this is out of scope of a chessboard, but I wanted to ask you how easy do you think it would be to modify the code to allow for more columns and rows?

I want to take a chessboard, generate a random map of green and blue tiles, and use it for a tabletop / mini simulator.

I am going to try to integrate this with slack.

Again, I know this is out of scope of your project, but just figured i'd ask you before I forked.

**Comment by oakmac** [comment]
I don't know what you mean by "tabletop / mini simulator"

Creating a random board of NxN squares shouldn't be too difficult with a little HTML + CSS + JS knowledge. I'm not even sure I would fork chessboard.js for that purpose.

**Comment by bokybanton** [comment]
Casablanca chess has 10x10 board and two more pieces
