### ISSUE TITLE
Promotion Popup

### ISSUE THREAD

**Issue by crapomat** [oakmac/chessboardjs#116]
Hi, 
I took a look at http://chessboardjs.com/examples#5000 and saw the line "promotion: 'q'" and the comment. How do you create a popup dialog here? I saw it on lichess.org that it is possible, but i don't know how they made it. I opened this "issue" because there is no info about promotions in docs and examples.

**Comment by oakmac** [comment]
chessboard.js is ["just a board"](https://github.com/oakmac/chessboardjs#what-is-chessboardjs-not)

Pawn promotion is outside the scope of chessboard.js
