### ISSUE TITLE
HTML example that works

### ISSUE THREAD

**Issue by ZenLearner** [oakmac/chessboardjs#119]
Hi,

Many thanks for creating chessboard.js and chess.js. I have been using pgn4web for years now and this is EXACTLY the improvement I needed, a modular js/css biased solution.

I would need something really simple: and HTML example that worked. I have tried the siansell example (after downloading to a local directory on my Mac)but did not work. (the board is not shown)

The only example that works was provided by bmarini on a similar piece of code chess, but it is 8 years old now. https://github.com/bmarini/jchess it works, but I guess the new features of chess and board chess are not incorporated.

Excuse that my knowledge is very limited, but I have managed to use pgn4web extensively. The author, Paolo Casaschi provides HTML examples that I can modify.

The chessboard.js and chess.js seem a lot simpler than pgn4web but I need an HTML example to test locally. Thx.

**Comment by oakmac** [comment]
Every example on [chessboardjs.com/examples] has a link to "View example in new window", which is a simple HTML page that demonstrates the example.

[chessboardjs.com/examples]:http://chessboardjs.com/examples

**Comment by oakmac** [comment]
For example (no pun intended), here is the link for Example 1000: http://chessboardjs.com/examples/1000

**Comment by ZenLearner** [comment]
Got it. VERY POWERFUL. Thx a lot!

I may know little, but can learn! :-) (good at my age!)


> On 23 Mar 2016, at 16:58, Chris Oakman <notifications@github.com> wrote:
> 
> For example (no pun intended), here is the link for Example 1000: http://chessboardjs.com/examples/1000 <http://chessboardjs.com/examples/1000>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/oakmac/chessboardjs/issues/119#issuecomment-200410409>

Fernando Semprun
