### ISSUE TITLE
User vs User

### ISSUE THREAD

**Issue by Maeggi** [oakmac/chessboardjs#136]
Hi,
have any a idea for User vs User with mysqli?
The Example on "http://chessboardjs.com/examples#5002"
is Com vs Com.
But, how can i Save, Load and Update the Data on Database with my User?

Thanks for Help

**Comment by oakmac** [comment]
chessboard.js is only for the JavaScript board that exists in the browser. This question is out of scope for this project.

**Comment by Maeggi** [comment]
Yes i know. I still use chess.js.
There stands, need a user interface? Try Chris Oakman's excellent chessboard.js library.
But, i found not Examples for User vs User :)
