### ISSUE TITLE
cljs branch

### ISSUE THREAD

**Issue by jiangts** [oakmac/chessboardjs#137]
was wondering if there was any development on the cljs branch.

otherwise, I'm considering writing my own cljs react chessboard component, seems like a lot of fun.

**Comment by oakmac** [comment]
> was wondering if there was any development on the cljs branch.

Not at this time.

I wouldn't mind re-writing chessboard.js using ClojureScript, but I think it works better as a small library written in JavaScript.

I would like to remove the jQuery dependency, but piece animations would be tricky.
