### ISSUE TITLE
Highlight legal moves as circles (like lichess)

### ISSUE THREAD

**Issue by GabrielPereyra** [oakmac/chessboardjs#140]
Is there any easy way to do this ([example](https://en.lichess.org/tCB4XPLE))?

**Comment by oakmac** [comment]
You can use chessboard.js with [chess.js] to highlight legal moves: [Example 5003]

[chess.js]:https://github.com/jhlywa/chess.js
[Example 5003]:http://chessboardjs.com/examples#5003
