### ISSUE TITLE
Creation of git tags

### ISSUE THREAD

**Issue by gonzalezjo** [oakmac/chessboardjs#161]
If a git tag were to be created, chessboard.js would be supported by cdnjs, which would be great for the library. (See here: https://github.com/cdnjs/cdnjs/issues/12943#issuecomment-431529802 )

Edit: I feel like I should be elaborating on why git tags are nice. For one, by being on cdnjs, (which requires git tags) chessboard.js gets automatically hosted, minified, and cache-configured on Cloudflare's edge network, which is sweet. Besides that, though, it lets you add npm hooks, which might help with deployment for some users.

**Comment by oakmac** [comment]
What tag(s) are needed for this?

**Comment by marvinIsSacul** [comment]
I think the _version_ tags.

**Comment by gonzalezjo** [comment]
Yes. If you set up tags properly, and have an interest in getting chessboard.js on npm, you could follow [these steps](https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md) to add both set up tags, and do everything needed to setup autoupdate hooks for an npm package.

**Comment by oakmac** [comment]
I tagged [Commit #4e21c9bbfb](https://github.com/oakmac/chessboardjs/commit/4e21c9bbfbc8cecd2e76c46c043d47a884f44d3c) as "v0.3.0"

Will be sure to do this in the future.

**Comment by oakmac** [comment]
FYI - I just published v1.0.0 on [npm](https://www.npmjs.com/package/@chrisoakman/chessboardjs) and added links to the [unpkg CDN](https://unpkg.com/) urls on the [website](https://chessboardjs.com/download)
