### ISSUE TITLE
Proper Fen String

### ISSUE THREAD

**Issue by folksgl** [oakmac/chessboardjs#164]
A proper FEN string has six fields as seen here: [https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation)

Using improper FEN string representations limits the maturity and flexibility that chessboard.js can achieve. Additionally, FEN is a **standard**. If it happens that you do not or will not implement according to the standard, then please do not use the term.

**Comment by oakmac** [comment]
From the [documentation](https://chessboardjs.com/docs#fen_string):

> Note that FEN notation captures more information than ChessBoard requires, like who's move it is and whether or not castling is allowed. This information will be ignored; only the position information is used.
