### ISSUE TITLE
Specify jQuery version in readme

### ISSUE THREAD

**Issue by 0x213F** [oakmac/chessboardjs#169]
**Summary**

I spent a fair amount of time debugging why the board wasn't working as expected. It turns out my jQuery v3.3.1 was not up to date enough. I see that the demo websites are running jQuery v3.4.1. I upgraded my jQuery and now things are working as expected.

**Proposal**

Can you specify the minimum jQuery version in the readme?

**Comment by Zenahr** [comment]
Seconded. It took me a full hour to get it working even though I've read the instructions on the website. Why is this still not inside the README? Is this project not being maintained anymore?

**Comment by oakmac** [comment]
> Can you specify the minimum jQuery version in the readme?

Done with [commit f093aaf4](https://github.com/oakmac/chessboardjs/commit/f093aaf4e99e5fcfc3a8f156ea5338205869cc28)

I'm sorry y'all had trouble with this; I agree it should be clear in the documentation. The minimum jQuery version is specified in the [package.json](https://github.com/oakmac/chessboardjs/blob/f093aaf4e99e5fcfc3a8f156ea5338205869cc28/package.json#L13-L15) file, but that is pretty obscure unless you know to look for it.

> Is this project not being maintained anymore?

I do not have any current plans for big changes for chessboard.js in the near future, but I have not ruled out working on a v2 completely. Meanwhile, I'm around to watch the repo for small stuff like this :wink:
