### ISSUE TITLE
SparePieces error: Cannot read property 'left' of undefined when using orientation

### ISSUE THREAD

**Issue by nganphtgit** [oakmac/chessboardjs#174]
I want to use spare pieces and allow to change orientation of the board, then I got the error

**Comment by oakmac** [comment]
Can you share the code that is producing this error?

**Comment by nganphtgit** [comment]
Ohh, I see that I can using flip board for my function, sorry for bothering you.

**Comment by oakmac** [comment]
No worries :smile: Glad things are working!
