### ISSUE TITLE
PGN viewer

### ISSUE THREAD

**Issue by TowelSniffer** [oakmac/chessboardjs#176]
I am hoping to set this up as a way to test tactics based on a given pgn. from here: https://chessboardjs.com/examples#5000 Could it be set up to only allow moves according to a pgn string?

**Comment by oakmac** [comment]
> Could it be set up to only allow moves according to a pgn string?

Yes - this should be possible by integrating with the [chess.js library](https://github.com/jhlywa/chess.js).

**Comment by TowelSniffer** [comment]
Ok thanks for you help
