### ISSUE TITLE
Web component / ES2017 version?

### ISSUE THREAD

**Issue by justinfagnani** [oakmac/chessboardjs#182]
For fun I've been working on a port of this project to ES2017 and web components.

I think the UX of a web component version is really nice. Instead of having to new up a chessboard with JavaScript, you can just use HTML:

```html
<chess-board></chess-board>
```

Most configuration options are available as HTML attributes:

```html
<chess-board
    position="r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R"
    orientation="black" 
    draggable-pieces
    spare-pieces
    hide-notation
    drop-off-board="snapback"
    piece-theme="img/chesspieces/alpha/{piece}.png"
    move-speed="slow"
    snapback-speed="500"
    snap-speed="100">
</chess-board>
```

You can still interact with the component via JS:

```js
const board = document.querySelector('chess-board');
board.move('e2-e4');
```

And the callback style events are converted to custom DOM events:

```js
board.addEventListener('drag-start', (e) => {
  const {piece, orientation} = e.detail;
  if ((orientation === 'white' && piece.search(/^w/) === -1) ||
      (orientation === 'black' && piece.search(/^b/) === -1)) {
    e.preventDefault();
  }
});
```

Along the way I've been removing jQuery, as it seems like plain JS APIs handle most things quite well now.

The board is rendered into a shadow root, so the implementation can be a bit simpler. CSS classes don't need to be manually scoped anymore, for instance. I'm still working on enabling customizable styling.

All-in-all this is a great library and the port has been relatively straight forward! Would you be interested in me contributing it back? It is a breaking change, but I think the usability wins are really nice, and it will be a lot easier to use inside of frameworks like React, Angular, etc., because with properties and attributes exposed on the element, data binding will just work. I've updated almost all of the examples and the documentation as well. I'm interested in porting to TypeScript as well, which I think would make it easier to read and track the different data types used internally.

I think this port would either fix or be a good start on #50, #169, #157, #152, #148, and I'd love to tackle #126, #5, and resize related issues (by using ResizeObserver) too.

Thanks for this awesome library!

**Comment by justinfagnani** [comment]
In case you're interested, I have my fork up here: https://github.com/justinfagnani/chessboardjs

It's a pretty extensive rewrite in some areas, especially rendering where I tried to go 100% declarative with lit-html, and write dragging and animations as state changes. I'm sure you might not be interested in all that.

Other things you might be though. It uses JS modules, CSS grid (no float), CSS transitions for all animations, removes jQuery, and has tight CSS scoping. All the animated pieces and the dragging piece are inserted into the element's shadow root, so they don't need generated IDs, and nothing needs scoped CSS classes. All the important elements in the shadow root are exported as [CSS shadow parts](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) so they're styleable from the outside, like:

```css
chess-board::part(black) {
  background: black;
}
chess-board::part(highlight) {
  border-color: blue;
}
```

I tried to get the website up on Glitch, so you can check out the examples. I think that's working, but it's been a little flaky: https://justinfagnani-chessboardjs.glitch.me/website/index.html

**Comment by oakmac** [comment]
This is some really strong work! Thank you for the kind words about the library :)

Given the degree of changes here I think a fork is a better option than contributing upstream for now.

**Comment by justinfagnani** [comment]
Ok. I couldn't stop myself from going down the lit-html path once I got going, so I figured that'd be likely. There might be useful commits in there along the way if you get interested in anything in there being upstreamed.

I'll publish this with a new name, and change the site to look visually enough different, and add in some attribution back to you.

Thanks!!
