### ISSUE TITLE
Turn off default highlighting

### ISSUE THREAD

**Issue by hashlib** [oakmac/chessboardjs#184]
The chessboardjs comes with default yellow highlighting, I didn't find any option to turn it off.

**Comment by oakmac** [comment]
The recommended way to change the square highlighting color is by adding your own CSS.

The selector needed to override can be found [here](https://github.com/oakmac/chessboardjs/blob/f2b0c8928b264a3e75be2198a81743196218c348/lib/chessboard.css#L35)
