### ISSUE TITLE
OnSnapEnd() and OnMoveEnd()

### ISSUE THREAD

**Issue by ScarecrowY** [oakmac/chessboardjs#188]
Hi, could you please explain what is the difference between these two functions? In the documentation, it says that OnMoveEnd() is called when the "snap" animation is completed. I am a  little confused about what "'snap' animation" specifically means here. Thank you so much!

**Comment by oakmac** [comment]
When a piece is dropped on a square, it will quickly animate to the center of the square. This animation is the "snap" being referenced here. ie: the piece "snaps" to the center of the square. This event will only fire after a user has dropped a dragged piece (see the [dropDraggedPieceOnSquare](https://github.com/oakmac/chessboardjs/blob/f2b0c8928b264a3e75be2198a81743196218c348/lib/chessboard.js#L1245-L1277) function).

`onMoveEnd` fires at the completion of all animations when the board position changes. This usually happens programmatically by calling `board.position(newPosition)` (or a variant of that method - there are several alias that cause the board position to change).

Note that `onMoveEnd` and `onChange` happen at different times: the board's internal position is considered to be changed instantly, and `onMoveEnd` will fire later after piece animations finish.

**Comment by ScarecrowY** [comment]
Thank you so much for such detailed explanation. But here I am still a little confused, because onSnapEnd sounds like onMove. What are the difference between these two?

**Comment by ScarecrowY** [comment]
Sorry for bothering, could you please explain the difference between OnSnapEnd() and OnDrop() if you saw this message? I think that was my original confusion. I would really appreciate your help!

**Comment by oakmac** [comment]
`onDrop()` fires as soon as the mouse button is released when dragging a piece - see [Example 4004](https://chessboardjs.com/examples#4004). Note that it does not matter where the piece was dropped (on a square, off the board) - this event always fires as soon as the mouse button is released.

`onSnapEnd()` fires after the quick animation where a piece centers itself onto a square. Thus, `onSnapEnd()` always happens _after_ an `onDrop()` event, and only when a piece has been dropped onto a square (not off of the board).

**Comment by oakmac** [comment]
Another way of thinking about this: after an `onDrop()` event, there might still be animation occurring on the board as a piece snaps to the center of a square. `onSnapEnd()` happens after all of the animation stops (when a piece has been dropped onto a square).

**Comment by ScarecrowY** [comment]
Thank you so much!
