### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by gmolaire** [oakmac/chessboardjs#193]
Hi there! Is it possible to update the npm package? Moreover, having a github action do it would be ideal. No more manual requests.

**Comment by faeb187** [comment]
when I install the NPM package `chessboardjs` it depends on version 0.0.1 (instead of 1.0.0) I'm assuming this was asked in this issue, am I right?

**Comment by oakmac** [comment]
@faeb187 I am sorry you have had some troubles with all of this.

> Looks like there was another guy forking your repo when it was v0.0.1 and now it's misleading

Yes - I believe someone forked this project and pushed it to npm at some point in the past.

> You should communicate this

The [download page](https://chessboardjs.com/download) lists the scoped package `@chrisoakman/chessboardjs`

> It's a huge mess anyway, the typings @types/chessboardjs are kinda linked to the v0.0.1 too it seems

I am not involved with `@types/chessboardjs`

**Comment by oakmac** [comment]
>  Is it possible to update the npm package?

[`@chrisoakman/chessboardjs`](https://www.npmjs.com/package/@chrisoakman/chessboardjs) contains the latest release of this library

**Comment by oakmac** [comment]
I [updated the README](https://github.com/oakmac/chessboardjs/commit/bfb9315cd44d22c4a3ccc883ab4c0b42e902557e) with clearer links to the scoped npm package.
