### ISSUE TITLE
I'm not able use this package with react.

### ISSUE THREAD

**Issue by CuriosBasant** [oakmac/chessboardjs#201]
It doesn't exports anything, rather it just add the `ChessBoard` to global `window`.
Please guide me

**Comment by oakmac** [comment]
It is possible to use this library with React via hooks and/or component lifecycle events. You will have to bridge the state of the board with however you are managing state in React (components, Redux, etc).

You may want to check out [Chessboard.jsx] as an alternative too.

[Chessboard.jsx]:https://chessboardjsx.com/
