### ISSUE TITLE
PIeces showing up as broken links

### ISSUE THREAD

**Issue by compugator2** [oakmac/chessboardjs#203]
I included the unpkg css and js files as expressed.  My board shows up with the a-h and 1-9 but the images show as broken links.  Am I missing something?

I saw where some people were saying to modify the js file but since it is CDN I cannot do that.

**Comment by oakmac** [comment]
You may need to host the image files somewhere locally.

Hard to diagnose without more information / details about your setup.

**Comment by compugator2** [comment]
That's what it was.  Sorry to bother you.

**Comment by oakmac** [comment]
> Sorry to bother you.

No worries :smiley: 

I'm glad you were able to figure it out!

**Comment by dipamsen** [comment]
same issue...
I don't get why i would have to host the images..

**Comment by adnjoo** [comment]
I copied the chessboard.js file from the cdn and changed this line on line 579 from
`config.pieceTheme = 'img/chesspieces/wikipedia/{piece}.png'` to 
`config.pieceTheme =  'https://chessboardjs.com/img/chesspieces/wikipedia/{piece}.png'`

**Comment by oakmac** [comment]
> I copied the chessboard.js file from the cdn and changed the code on line 579 from
config.pieceTheme = 'img/chesspieces/wikipedia/{piece}.png' to
config.pieceTheme = 'https://chessboardjs.com/img/chesspieces/wikipedia/{piece}.png'

FYI @dipamsen @adnjoo - I do not recommend hosting the chess piece images from the chessboardjs.com domain. That is a small web server that I pay for; it is not designed to handle a lot of web traffic.

I should be able to publish the chess piece images to the unpkg.com CDN via the npm publish process. See [Issue #231](https://github.com/oakmac/chessboardjs/issues/231).

**Comment by balerion45** [comment]
> That's what it was. Sorry to bother you.

Can you tell me how to store the images of pieces locally?!

**Comment by balerion45** [comment]
> That's what it was. Sorry to bother you.

can you please tell me how to do it!

**Comment by balerion45** [comment]
> same issue... I don't get why i would have to host the images..
> 
> Using this currrently:
> 
> ```js
> $('img').each((i, e) => e.setAttribute("src", "https://chessboardjs.com/" + e.getAttribute("src")))
> ```

can you explain how to use this??

**Comment by dipamsen** [comment]
@balerion45 you can download the image files and store it in the required folder (`img/chesspieces/wikipedia/`)
