### ISSUE TITLE
One Play Per Turn

### ISSUE THREAD

**Issue by compugator2** [oakmac/chessboardjs#204]
Is there a way to allow only 1 play when the board becomes visible?  I am trying to set up a correspondence chess game but cannot have one person playing both sides.  White plays then should not be able to do anything further until black plays.

I tried adding this to the end of onDrop but it didn't work:

var childNodes = document.getElementById("board1").getElementsByTagName('*');
for (var node of childNodes) {
  node.disabled = true;
}

**Comment by oakmac** [comment]
I think [Example 4002](https://chessboardjs.com/examples#4002) might be similar to what you are looking for.

**Comment by compugator2** [comment]
That looks like it would work, but I use the following code and I can still seem to move the other side's pieces after I move.

function onDragStart (source, piece, position, orientation) {
    // do not pick up pieces if the game is over
    if (game.game_over()) return false;

    // only allow pieces to be dragged when the board is oriented in their direction
    if ((orientation === 'white' && piece.search(/^w/) === -1) ||
        (orientation === 'black' && piece.search(/^b/) === -1)) {
        return false;
    }
  
    // only pick up pieces for the side to move
    if ((game.turn() === 'w' && piece.search(/^b/) !== -1) ||
        (game.turn() === 'b' && piece.search(/^w/) !== -1)) {
        return false;
    }
}

**Comment by compugator2** [comment]
Yeah that did it.  It didn't seem to work at first until I did a hard refresh on my page to correct for the updated js file.  Thanks again.
