### ISSUE TITLE
Highlight when check

### ISSUE THREAD

**Issue by william-song-shy** [oakmac/chessboardjs#207]
In some website like lichess etc.,the king will be highlight if it is being checked.Do you have this feature here?
I'm a chinese so maybe it is a little difficult to undeerstand what I said.Please understand.

**Comment by pablorodriguez-paraport** [comment]
Hi @william-song-shy! I don't think chessboard.js has a built-in feature to highlight a check. The library only renders the board and the pieces, it doesn't actually know the rules of chess. It can be integrated with chess.js to identify the check and, from the chessboard.js examples, there are ways to highlight board squares and pieces. So, in combination, you can get the desired result. Unfortunately, I don't have a working code to share. I hope this helps!

**Comment by william-song-shy** [comment]
> Hi @william-song-shy! I don't think chessboard.js has a built-in feature to highlight a check. The library only renders the board and the pieces, it doesn't actually know the rules of chess. It can be integrated with chess.js to identify the check and, from the chessboard.js examples, there are ways to highlight board squares and pieces. So, in combination, you can get the desired result. Unfortunately, I don't have a working code to share. I hope this helps!

Thanks for your advice ! I wonder know how to highlight the piece to show it's being checked like that
![image](https://user-images.githubusercontent.com/47596959/106006929-b630c880-60f0-11eb-8248-7d74e78fb67f.png)
.

**Comment by william-song-shy** [comment]
> Hi @william-song-shy! I don't think chessboard.js has a built-in feature to highlight a check. The library only renders the board and the pieces, it doesn't actually know the rules of chess. It can be integrated with chess.js to identify the check and, from the chessboard.js examples, there are ways to highlight board squares and pieces. So, in combination, you can get the desired result. Unfortunately, I don't have a working code to share. I hope this helps!

Thanks for your advice ! I wonder know how to highlight the piece to show it's being checked like that
![image](https://user-images.githubusercontent.com/47596959/106006929-b630c880-60f0-11eb-8248-7d74e78fb67f.png)
.

**Comment by oakmac** [comment]
This is possible using CSS with a [radial-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient()) on the square where the King is located.

**Comment by william-song-shy** [comment]
> This is possible using CSS with a [radial-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient()) on the square where the King is located.

May be.I wonder know will it be a built-in feature in the future?
