### ISSUE TITLE
Board redrawing on resize

### ISSUE THREAD

**Issue by sachinsu** [oakmac/chessboardjs#59]
Hi,

First of all thanks for wonderful library. I have been  trying to use the same, however on resize of the browser window or change of orientation, the chess board is redrawn and initialized again.  

Any way to retain state of the board.

Any Help is much appreciated.

**Comment by hcgreier** [comment]
Hello folks,
i have a similar problem here. I have set the squares of the chess board in different colors (light gray/blueish). Now when I use the resize method (change size of browser window...), the board is redrawn and my custom color settings are gone and replaced by the default...

Does anyone have an idea?
hello,
hc
