### ISSUE TITLE
Where is the board position loaded to the window? 

### ISSUE THREAD

**Issue by theideasmith** [oakmac/chessboardjs#72]
I am a newbie to Javascript, and was wondering if somebody could point* me towards the location in the source code for chessboardjs in which the position itself is loaded into the "window" object. I am looking to develop a chess engine running on PHP, using the chessboardjs UI, and want to fully understand the API before proceeding with my project. 
A pointer* would very much be appreciated. 
Thanks

**Comment by oakmac** [comment]
Take a look at [Example #3000](http://chessboardjs.com/examples#3000).
