### ISSUE TITLE
How to customize the chess board background?

### ISSUE THREAD

**Issue by ngocdaothanh** [oakmac/chessboardjs#76]
Is there a way to customize the chess board? If there's no built-in way, can you share a guideline so that I can manually customize chess board?

Thanks.

**Comment by ExtremeCoolDude** [comment]
@ngocdaothanh  Hello can you pls elaborate further how you achieved the background, when I follow your instructions I get this : 

![image](https://user-images.githubusercontent.com/50034073/108638933-d66a6200-74b9-11eb-9318-d250d4736083.png)

**Comment by ExtremeCoolDude** [comment]
Nevermind `background-image('') `works
