### ISSUE TITLE
Change images for fonts.

### ISSUE THREAD

**Issue by salvador-dali** [oakmac/chessboardjs#80]
I noticed that all images for (pawn, king, rook, ...) have just two colors. Which suggests to use web-fonts instead. This way you will have only one http request (instead of 12), the size will be smaller and it will look sharp on any device with any zoom.

Have you thought about changing images for fonts?

**Comment by oakmac** [comment]
FYI - Issue #113 has a nice solution here using a data-uri

I originally choose not to use fonts in order to allow piece themes with colors.
