### ISSUE TITLE
 I need help for chessboardjs - 0.3.0

### ISSUE THREAD

**Issue by italianplayer** [oakmac/chessboardjs#90]
hello , I am a chessplayer little good with the code . I downloaded chessboardjs - 0.3.0 which contains js css and img but not a index.htm . So I tried to make one to upload your js . but the page does not display anything. can you help? really thanks
my test is http://italianplayer64.altervista.org/test/index.htm
in the index I wrote:
in the head call .....
....css/chessboard-0.3.0.min.css" />
.....css/chessboard-0.3.0.css" />
.....script src="js/chessboard-0.3.0.js"></script>
......script src="js/chessboard-0.3.0.min.js"></script>
in the body call
....div id="board1" style="width: 400px">
and script 	
		var board1 = new ChessBoard('board1', 'start');
	
....

**Comment by oakmac** [comment]
You need to include [jQuery](http://jquery.com/) on the page.

**Comment by italianplayer** [comment]
Thanks , now it works! http://italianplayer64.altervista.org/test2/index.htm
 I would just like to know how I can load a pgn and if I can filter with a parameter . eg [ white = " xxxxx " ]
really many thanks!!
