### ISSUE TITLE
Incorrect SAN generated.

### ISSUE THREAD

**Issue by tforbus** [oakmac/chessboardjs#91]
![screen shot 2015-02-10 at 21 26 25](https://cloud.githubusercontent.com/assets/1789549/6142448/82557ed8-b16b-11e4-9986-0ff967dde1df.png)

In the image attached, the knight on C3 is absolutely pinned.
The next move made is Nge2, but the SAN generated is Ne2.

FEN:
```
rn2k2r/pppq1ppp/5p2/3p4/1b1P4/2NQP3/PPP2PPP/R3K1NR w KQkq - 0 1
```

**Comment by oakmac** [comment]
chessboard.js has no knowledge of the game of chess; this seems like a [chess.js](https://github.com/jhlywa/chess.js) question?
