### ISSUE TITLE
Feature Request: Let the pieceTheme function know the location of the piece

### ISSUE THREAD

**Issue by charlesguse** [oakmac/chessboardjs#93]
Currently the object being passed into pieceTheme(piece) is just a string of the piece (wP, bN, etc) but it would be nice to also know where the piece (or maybe going from, to in the case of animation) so that you can do things like make the most recent move transparent (my goal) or outline the piece as another example.

Here is the method in question: http://chessboardjs.com/examples#2030

Also, great library! Thanks for working on it.

**Comment by oakmac** [comment]
Thanks for the kind words :)

I think your use case is covered with either the [onChange](http://chessboardjs.com/docs#config:onChange) or [onMoveEnd](http://chessboardjs.com/docs#config:onMoveEnd) events. Examples [4000](http://chessboardjs.com/examples#4000) and [4012](http://chessboardjs.com/examples#4012).

`pieceTheme()` is only called when markup for a new piece is needed.
