### ISSUE TITLE
v1.0.0 Release

### ISSUE THREAD

**Issue by oakmac** [oakmac/chessboardjs#96]
There hasn't been much active development on this project in the last year or so. IMO, this is largely a good thing as it means the API is stable and people aren't filling lots of bugs or strongly requesting changes.

Probably appropriate to do some cleanup and create a v1.0.0 release. I'll use this issue to track progress on the first major version release.

FYI: @fhinson, re your comment in Issue #34

**Comment by ngocdaothanh** [comment]
:+1:

**Comment by davidmpaz** [comment]
nice!

**Comment by fhinson** [comment]
@oakmac great to hear! I've just made a PR with a fix for piece flickering. Happy to contribute to the library more for the v1.0.0 release.

**Comment by ngdaddikar** [comment]
Great!

**Comment by jbkunst** [comment]
+1

**Comment by oakmac** [comment]
FYI - I just published v1.0.0 on [npm](https://www.npmjs.com/package/@chrisoakman/chessboardjs)

Better late than never :wink:

**Comment by vesper8** [comment]
@oakmac better late than never sure but would have been very nice however if you merged some of the PRs such as click-to-move and board themes.. specially the click-to-move.. add it as an experimental feature if you don't feel it's sturdy enough.. but it's really lacking imo
