### ISSUE TITLE
Issue with draggable option

### ISSUE THREAD

**Issue by tgoldenberg** [oakmac/chessboardjs#98]
I am using Pusher for two player interaction. However, I am unable to toggle the :draggable attribute for cfg. I tried setting cfg.draggable = false after each move, and setting back to true after opponent's move, but this isn't working. Any suggestions? 

Also, I am trying to present the captured pieces in a side bar. I saw the code related to this, just wondering if there's an easy solution you have prepared already? That would make it easier, thanks! 

BTW, great project!

**Comment by oakmac** [comment]
The `draggable` property is not designed to be changed after the board has been created. Take a look at [Example 4002](http://chessboardjs.com/examples#4002), I think it's what you're looking for.

There is no code for showing captured pieces; you'll have to write that custom to your project.

Thanks for the kind words; glad you like the project :)

**Comment by tgoldenberg** [comment]
Yes, the onDragStart was what I needed to use, thank you! 

Maybe I'll share the code for showing captured pieces once its ready, and you can incorporate if you like? I think it's a reasonable option to include :)

**Comment by tgoldenberg** [comment]
for others who may be interested, here is the code I used, in Rails: 
var onDragStart = function(source, piece, position, orientation) {
  if (game.game_over() === true ||
      (game.turn() === 'w' && "<%= current_user.id %>" === "<%= @room.player2_id %>") ||
      (game.turn() === 'b' && "<%= current_user.id %>" === "<%= @room.player1_id %>") ||
      (game.turn() === 'w' && piece.search(/^b/) !== -1) ||
      (game.turn() === 'b' && piece.search(/^w/) !== -1)) {
    return false;
  }
};
